#!/usr/bin/env python3
"""Generate _assets/template_v1/assets/css/icons.css from Font Awesome SVGs.

Replaces Font Awesome's all.min.js (1.4 MB) with ~6 KB of CSS: every
<i class="fab fa-twitter"> keeps working, drawn as a CSS mask in currentColor.
One-off: re-run only when an icon is added to ICONS (the build doesn't run it).

    python3 _build/make_icons_css.py path/to/fontawesome-free-6.4.0-web/svgs

(The SVG sources aren't kept in the repo any more: download fontawesome-free-6.4.0-web.zip
from https://fontawesome.com/download and point the script at its svgs/ folder.)
"""
import re
import sys
from pathlib import Path
from urllib.parse import quote

# class used in templates -> svgs/<style>/<file>.svg (Font Awesome 6 names)
ICONS = {
    "fa-linkedin-in": "brands/linkedin-in",
    "fa-linkedin": "brands/linkedin",
    "fa-twitter": "brands/twitter",
    "fa-whatsapp": "brands/whatsapp",
    "fa-discord": "brands/discord",       # PEC community link
    "fa-youtube": "brands/youtube",
    "fa-envelope": "solid/envelope",
    "fa-map-marker-alt": "solid/location-dot",
    "fa-microphone": "solid/microphone",
    "fa-heart": "solid/heart",
    "fa-comments": "solid/comments",
    "fa-calendar-alt": "regular/calendar-days",
}

OUT = Path("_assets/template_v1/assets/css/icons.css")

HEADER = """/* Font Awesome Free 6.4.0 icons (CC BY 4.0, https://fontawesome.com/license/free),
   drawn as CSS masks so <i class="fab fa-..."> needs no JavaScript.
   Generated by _build/make_icons_css.py - edit ICONS there, don't edit this file. */
.fa,.fas,.far,.fab{display:inline-block;height:1em;width:1em;vertical-align:-.125em;
background-color:currentColor;-webkit-mask:var(--fa-i) center/contain no-repeat;mask:var(--fa-i) center/contain no-repeat}
.fa-fw{width:1.25em}
"""


def main(svg_dir):
    lines = [HEADER]
    for cls, name in ICONS.items():
        svg = (Path(svg_dir) / f"{name}.svg").read_text()
        svg = re.sub(r"<!--.*?-->", "", svg)
        w, h = map(float, re.search(r'viewBox="0 0 (\S+) (\S+)"', svg).groups())
        uri = "data:image/svg+xml," + quote(svg, safe=" /:=\"'")
        lines.append(f".{cls}{{--fa-i:url(\"{uri.replace(chr(34), chr(39))}\");width:{w / h:.4g}em}}\n")
    # .fa-fw must win over the per-icon width
    lines.append(".fa-fw.fa,.fa-fw.fas,.fa-fw.far,.fa-fw.fab{width:1.25em}\n")
    OUT.write_text("".join(lines))
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes, {len(ICONS)} icons)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
