#!/usr/bin/env python3
"""Self-host the Google Fonts the sites use: writes _assets/template_v1/assets/fonts/*.woff2
and _assets/template_v1/assets/css/fonts.css (latin + latin-ext subsets only; the browser
downloads latin-ext only on pages that need it, e.g. Polish names).

Replaces two render-blocking requests to fonts.googleapis.com (+ fonts.gstatic.com),
i.e. two extra DNS/TLS round trips, on every page. One-off: re-run only to change fonts.

    python3 _build/make_fonts_css.py
"""
import re
import urllib.request
from pathlib import Path

CSS_URL = ("https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800"
           "&family=Roboto:wght@300;400;700&family=Monoton&display=swap")
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/129 Safari/537.36")  # a modern UA gets woff2
KEEP = ("latin", "latin-ext")
ASSETS = Path("_assets/template_v1/assets")


def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA})).read()


def main():
    css = get(CSS_URL).decode()
    out, fetched = [], {}
    (ASSETS / "fonts").mkdir(parents=True, exist_ok=True)
    for subset, block in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S):
        if subset not in KEEP:
            continue
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        family = re.search(r"font-family: '([^']+)'", block).group(1).lower()
        name = fetched.get(url)
        if name is None:
            name = f"{family}-{subset}-{len(fetched)}.woff2"
            (ASSETS / "fonts" / name).write_bytes(get(url))
            fetched[url] = name
        out.append(block.replace(url, f"../fonts/{name}"))
    header = "/* Self-hosted Google Fonts (SIL OFL / Apache 2.0). Generated by _build/make_fonts_css.py */\n"
    (ASSETS / "css" / "fonts.css").write_text(header + "\n".join(out) + "\n")
    total = sum((ASSETS / "fonts" / n).stat().st_size for n in fetched.values())
    print(f"Wrote fonts.css: {len(out)} @font-face rules, {len(fetched)} woff2 files, {total // 1024} KB")


if __name__ == "__main__":
    main()
